services:
  nro-server:
    build: .
    container_name: nro_server
    working_dir: /app
    ports:
      - "14445:14445"
    depends_on:
      - mysql
    command: sh -c "sleep 20 && dotnet bin/Debug/net5.0/NRO_Server.dll"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

  mysql:
    image: mysql:8.0
    container_name: nro_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mysql_data:

